os:
  - osx
  - linux
  - windows
sudo: required
language:            node_js
node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"
env:
  - ENV=CI

before_install:
  - npm install -g npm@latest

install:
  - npm install --unsafe-perm=true

script:
  - npm run test

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
